name = "make-me-a-wizard"
main = "src/index.ts"
compatibility_date = "2023-12-18"
workers_dev = true

[[kv_namespaces]]
binding = "KV"
id = "937dcc5e89ae43f686cdb166a56743be"
preview_id = "2741410f9eb94bcb925a7fc4c02eb99f"

[[d1_databases]]
binding = "repl_demo_2025_d1"
database_name = "repl-demo-2025-d1"
database_id = "ca56a7f3-1f53-416e-90a4-5b22a549efea"

[[r2_buckets]]
binding = "R2"
bucket_name = "repl-demo-2025"

[[routes]]
pattern = "demo.xianwen.dev"
custom_domain = true

[[workflows]]
name = "photo-processing"
binding = "PHOTO_PROCESSING_WORKFLOW"
class_name = "PhotoProcessingWorkflow"

# Enable Workers Logs
[observability]
enabled = true

[env.production]
name = "make-me-a-wizard"

[env.staging]
name = "make-me-a-wizard-staging"
